name: Tmo Nightly Main Upstream Mirror

on:
  workflow_dispatch:
    branches: [ tmo-main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 6 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git checkout main
          git rev-parse HEAD
          currentBranch=$(git rev-parse --abbrev-ref HEAD)
          if [ $currentBranch == "main" ];
          then
            git remote set-url origin https://github.com/zephyrproject-rtos/zephyr.git
            git pull
            git remote set-url origin https://github.com/tmobile/DevEdge-IoTDevKit-ZephyrRTOS.git
            git push
          else
            echo "Not on main branch, exiting."
            exit 1
          fi
