name: Tmo Nightly Main Upstream Mirror

on:
  workflow_dispatch:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 6 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: mirror
        run: |
          currentBranch=$(git rev-parse --abbrev-ref HEAD)
          if [ $currentBranch == "main" ];
          then
            git remote set-url origin git@github.com:zephyrproject-rtos/zephyr.git
            git pull
            git remote set-url origin git@github.com:tmobile/DevEdge-IoTDevKit-ZephyrRTOS.git
            git push
          else
            echo "Not on main branch, exiting."
            exit 1
          fi
